apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Louis AS Grid Node
spec:
  description: 自動化網格交易機器人節點 - 24/7 智能交易
  icon: https://raw.githubusercontent.com/thankcoom/bitget-as/main/grid_node/logo.png
  coverImage: https://raw.githubusercontent.com/thankcoom/bitget-as/main/grid_node/logo.png
  tags:
    - Trading
    - Bot
    - Crypto
  variables:
    - key: USER_ID
      type: STRING
      name: 用戶 ID
      description: 從官網 Deploy 頁面複製（已自動填入）
    - key: NODE_DOMAIN
      type: DOMAIN
      name: 節點網域
      description: 為您的交易節點選擇一個網域
  readme: |
    # Louis AS Grid Node
    
    此節點將連接到官方伺服器，自動獲取您的交易配置並執行網格交易。
    
    ## 部署後操作
    1. 等待部署完成（約 1-2 分鐘）
    2. 複製生成的網域（如 `xxx.zeabur.app`）
    3. 返回官網設定頁面，貼上網域並儲存
    4. 開始交易！
    
    ## 注意事項
    - NODE_SECRET 會自動生成，請勿修改
    - 如需重新部署，請先在官網解除綁定
    
  localization:
    en:
      description: Automated grid trading bot node - 24/7 smart trading
      variables:
        - key: USER_ID
          name: User ID
          description: Copy from the official Deploy page (auto-filled)
        - key: NODE_DOMAIN
          name: Node Domain
          description: Choose a domain for your trading node
      readme: |
        # Louis AS Grid Node
        
        This node connects to the official server to automatically fetch your trading configuration and execute grid trading.
        
        ## After Deployment
        1. Wait for deployment to complete (~1-2 minutes)
        2. Copy the generated domain (e.g., `xxx.zeabur.app`)
        3. Return to the official Settings page, paste the domain and save
        4. Start trading!
        
  services:
    - name: grid-node
      icon: https://raw.githubusercontent.com/thankcoom/bitget-as/main/grid_node/logo.png
      template: PREBUILT
      domainKey: NODE_DOMAIN
      spec:
        source:
          image: ghcr.io/thankcoom/as-grid-node:latest
        ports:
          - id: web
            port: 8000
            type: HTTP
        env:
          AUTH_SERVER_URL:
            default: https://louisasgrid-api.zeabur.app
            readonly: true
          USER_ID:
            default: ${USER_ID}
          NODE_SECRET:
            default: ${PASSWORD}
            expose: true
        instructions:
          - type: TEXT
            title: Node URL
            content: https://${NODE_DOMAIN}
          - type: PASSWORD
            title: Node Secret
            content: ${NODE_SECRET}
            category: Credentials
